name: FartherViewDistance
version: ${project.version}
main: xuan.cat.fartherviewdistance.code.ChunkIndex
api-version: 1.13
softdepend: [PlaceholderAPI]
authors: [xuancat0208, EuSouVoce]
commands:
  viewdistance:
    usage: op
